import Home from "./Home";
import SignUp from "./SignUp";
import SignIn from './SignIn';
import Calendar from './Calendar';
import Timer from './Timer';
import Profile from './Profile';
import Setting from './Setting';
import Edit from './Edit';
import NotFound from './NotFound';
export { Home, SignUp, SignIn, Calendar, Timer, Profile ,Setting,Edit,NotFound};
